In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

In [3]:
enem = pd.read_csv('../src/enem_total_quali.csv')

enem.set_index('NU_INSCRICAO', drop=True, inplace=True)

enem.head()

,IN_BRAILLE,IN_AMPLIADA_18,IN_AMPLIADA_24,IN_LEDOR,IN_ACESSO,IN_TRANSCRICAO,IN_LIBRAS,APPROVED_ADM,APPROVED_MED,NU_ANO_2019,...,Q006_F,Q006_G,Q006_H,Q006_I,Q006_J,Q006_K,Q006_M,Q006_O,Q006_P,Q006_Q
NU_INSCRICAO,,,,,,,,,,,,,,,,,,,,,
190001237802,0,0,0,0,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,0,0
190001421548,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
190001592266,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
190001475147,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
190001867756,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0